### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by korny** [robotlolita/renpy-graph#1]
Sounds really interesting :) But I can't seem to find the actual code…only a README and some basic setup files. Is it possible that you forgot to commit a file?

**Comment by robotlolita** [comment]
In the end I never implemented it. I did make a change to Ren'Py to serialise the AST to analyse externally (https://github.com/robotlolita/renpy/commit/7c8f4ce5fb0ad9528db57bb43c10ea1d437fdeba), but that was all.

**Comment by korny** [comment]
I see, thanks for the quick answer! I used `grep` in the end to transform the script into a simplified outline - works pretty well.
